### ISSUE TITLE
Не вызывается исключение, если количество сыгранных часов отрицательное

### ISSUE THREAD

**Issue by Gena800** [Gena800/javaqa-teamwork#2]
### Описание
Если установить отрицательное время сыгранных часов не ловится RunTimeException
### Локация дефекта
https://github.com/Gena800/javaqa-teamwork/blob/bd3988e61622806844d9ac9d2b94b49595e24ea4/src/main/java/ru/netology/Player.java#L33-L41
### Шаги воспроизведения

1. Открыть класс [PlayerTest](https://github.com/Gena800/javaqa-teamwork/blob/Player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить [тест](https://github.com/Gena800/javaqa-teamwork/blob/bd3988e61622806844d9ac9d2b94b49595e24ea4/src/test/java/ru/netology/PlayerTest.java#L31)
#### Ожидаемый результат 
Выводится ошибка типа "Время игры не может быть отрицательным"
#### Фактический результат
Устанавливается отрицательное значение времени

### Окружение

- Операционная система: Windows 10 версия 1607
- IDE: Intellij IDEA Community Edition 2022.3.1
- Java: Open JDK 11

**Comment by Ishukov** [comment]
В методе play добавлено исключение RunTimeException для отрицательного значения игрового времени
